import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import NavBar from '@/components/navBar/NavBar';
import Header from '@/components/header/Header';
import { Providers } from './StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Gotoinc test',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className} suppressHydrationWarning={true}>
				<Providers>
					<div className='grid min-h-screen w-full overflow-hidden lg:grid-cols-[280px_1fr]'>
						<NavBar />
						<div className='flex flex-col'>
							<Header />
							<main className='flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6'>
								{children}
							</main>
						</div>
					</div>
				</Providers>
			</body>
		</html>
	);
}
