import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import NavBar from '@/components/navBar/NavBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Gotoinc test',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='grid grid-cols-5 gap-4'>
					<div className='col-span-1'>
						<NavBar />
					</div>
					<div className='col-span-4'>
						<main className='h-screen p-4 md:p-6'>{children}</main>
					</div>
				</div>
			</body>
		</html>
	);
}
